### ISSUE TITLE
it doesnt work on the lastest version of ctfd

### ISSUE THREAD

**Issue by Darkcast** [apt-42/apt42_ctfd_themes#7]
I am running the 3.3.0 in my local server and when I installed the theme It just crashes 

![2021-06-21_09-54](https://user-images.githubusercontent.com/1676655/122774105-ef6ffd80-d276-11eb-8399-7e05d4389771.png)

**Comment by avan-pra** [comment]
As stated in the README, the theme we made was made for v3.1.1.
Thanks for the issue, we may take a look at it soon.
As of now we recommand sticking to v3.1.1 of ctfd

**Comment by avan-pra** [comment]
Just tested it out on a fresh docker pull of ctfd, v3.3.0, no problem on my end.
The theme is working just like it should.
![Capture d’écran 2021-06-22 à 14 12 19](https://user-images.githubusercontent.com/47481450/122922659-25d77680-d364-11eb-8805-864cc139cbd9.png)
